"""TYPE_CHECKING-only structural contract for the routes/ mixin composition.

``SALTMDBHandler`` (routes/__init__.py) composes every feature mixin in this package
with ``ViewerHandlerBase`` at runtime, so each mixin's ``self.send_json(...)`` /
``self.get_db_connection()`` and ``ViewerHandlerBase``'s dispatch to
``self.get_entities(...)`` etc. are always valid in the real composed class. mypy
type-checks each file against its own declared bases in isolation and can't see that
final composition, so every one of those calls looks like a missing attribute. Giving
each mixin (and ``ViewerHandlerBase``) this ``Protocol`` as an extra, TYPE_CHECKING-only
base describes the full composed interface without changing anything at runtime --
outside TYPE_CHECKING it collapses to ``object`` at every use site, a no-op base every
class already has implicitly.
"""

from typing import Any, Protocol


class ViewerHandlerProtocol(Protocol):
    # Any, not a concrete server type: ViewerHandlerBase mixes this Protocol in
    # alongside http.server.BaseHTTPRequestHandler (whose own `server` is typed
    # `socketserver.BaseServer`) -- a narrower/unrelated type here would make mypy
    # reject the two base classes' `server` declarations as incompatible overrides.
    # Every real usage is `getattr(self.server, "some_attr", None)`, which doesn't
    # care about the precise type either way.
    server: Any

    def send_json(self, data, status: int = 200) -> None: ...
    def get_db_connection(self): ...

    def get_entities(self, query): ...
    def get_entity_detail(self, entity_id): ...
    def get_lineage(self, entity_id): ...
    def get_events(self, query): ...
    def get_tags(self): ...
    def get_all_relations(self, query): ...
    def get_entity_relations(self, entity_id, query): ...
    def get_relations_graph(self, query=None): ...
    def get_relations_neighborhood(self, query): ...
    def get_stats(self): ...
    def get_operations(self): ...
    def get_quality(self, query): ...
    def get_embeddings_stats(self): ...
    def get_search(self, query): ...
    def get_sessions(self, query): ...
    def get_scatterplot(self): ...
